### ISSUE TITLE
a(n-2) instead of a(n-1)

### ISSUE THREAD

**Issue by kckennylau** [Adriandmen/Oasis#2]
If an `A2` operator is at the beginning, let the second argument be `a(n-2)` instead of `a(n-1)`.

Currently it is useless, since `+` at the beginning became equivalent to `x`, and `*` to `²`, and `-` to `N`, and `÷` to `1`.

(Then, Fibonacci would be `+T`.)

**Comment by Adriandmen** [comment]
Done in the latest commit: https://github.com/Adriandmen/Oasis/commit/8af972b5835040d0a213696690070f38b5b61b3d
