### ISSUE TITLE
Add support for lists

### ISSUE THREAD

**Issue by ghost** [Adriandmen/Oasis#7]
Lists can be very useful when calculating some sequences, so it would be very useful to add support for lists (and also with 'mapping' operators when used on lists)

**Comment by Adriandmen** [comment]
Thanks! :)

I have added `L` as an `[1..N]` list and `R` as an `[N..M]` list. Most of the commands already map automatically, but I'll work on this later.

https://github.com/Adriandmen/Oasis/commit/8e99793da0504ad04e82a769b3bacb13c1be260e
